name: Deploy and Control NestJS App

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [ "Deploy and Control NestJS App" ]
    types:
      - requested
      - cancelled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to k3s Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.K3S_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.K3S_REGISTRY_URL }}/nestjs-app:${{ github.sha }} .
          docker push ${{ secrets.K3S_REGISTRY_URL }}/nestjs-app:${{ github.sha }}
          docker tag ${{ secrets.K3S_REGISTRY_URL }}/nestjs-app:${{ github.sha }} ${{ secrets.K3S_REGISTRY_URL }}/nestjs-app:latest
          docker push ${{ secrets.K3S_REGISTRY_URL }}/nestjs-app:latest

  notify-slack:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Notify Slack about the build
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "list_approve": "${{ secrets.SLACK_LIST_APPROVE }}",
              "title": "GitHub Action build result: ${{ job.status }}",
              "text": "Please check the commitment and approve if there are no problems.\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  approval-check:
    runs-on: ubuntu-latest
    needs: notify-slack
    if: ${{ github.event_name == 'workflow_run' && github.event.action == 'requested' }}
    steps:
      - name: Check for Approval
        id: check_approval
        run: |
          wait_time_seconds=300  # Timeout of 5 minutes
          check_interval_seconds=10 
          
          while true; do
            # Replace with your actual API call to fetch approval status
            approval_status=$(curl -s -u ${{ secrets.GITHUB_USERNAME }}:${{ secrets.GITHUB_TOKEN }}  https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals) 
          
            if [[ $approval_status == *"approved"* ]]; then
              echo "Workflow Approved"
              steps.check_approval.outputs.approved = 'true' # Set output for next job
              break
            elif [[ $approval_status == *"pending"* ]]; then
              echo "Waiting for approval..."
              sleep $check_interval_seconds
            else
              echo "Workflow not approved or cancelled. Exiting."
              exit 1
            fi
          
            # Adjust timeout based on your needs
            if [[ $SECONDS -ge $wait_time_seconds ]]; then
              echo "Approval timeout reached. Exiting."
              exit 1
            fi
          done

      - name: Continue if Approved
        if: ${{ steps.check_approval.outputs.approved == 'true' }}
        run: |
          echo "Workflow Approved"
          # Add your subsequent steps here

  cancellation-check: # New job to handle cancellation
    runs-on: ubuntu-latest
    needs: notify-slack
    if: ${{ github.event_name == 'workflow_run' && github.event.action == 'cancelled' }}
    steps:
      - name: Workflow Cancelled
        run: echo "Workflow has been cancelled"