name: Deploy on Approval

on:
  workflow_run:
    workflows: [ "Deploy and Control NestJS App" ]
    types:
      - requested
      - cancelled

jobs:
  approval-check:
    runs-on: ubuntu-latest
    needs: notify-slack
    if: ${{ github.event_name == 'workflow_run' && github.event.action == 'requested' }}
    steps:
      - name: Check for Approval
        id: check_approval
        run: |
          wait_time_seconds=300  # Timeout of 5 minutes
          check_interval_seconds=10 
          
          while true; do
            # Replace with your actual API call to fetch approval status
            approval_status=$(curl -s -u ${{ secrets.GITHUB_USERNAME }}:${{ secrets.GITHUB_TOKEN }}  https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals) 
          
            if [[ $approval_status == *"approved"* ]]; then
              echo "Workflow Approved"
              steps.check_approval.outputs.approved = 'true' # Set output for next job
              break
            elif [[ $approval_status == *"pending"* ]]; then
              echo "Waiting for approval..."
              sleep $check_interval_seconds
            else
              echo "Workflow not approved or cancelled. Exiting."
              exit 1
            fi
          
            # Adjust timeout based on your needs
            if [[ $SECONDS -ge $wait_time_seconds ]]; then
              echo "Approval timeout reached. Exiting."
              exit 1
            fi
          done

      - name: Continue if Approved
        if: ${{ steps.check_approval.outputs.approved == 'true' }}
        run: |
          echo "Workflow Approved"
          # Add your subsequent steps here

  cancellation-check: # New job to handle cancellation
    runs-on: ubuntu-latest
    needs: notify-slack
    if: ${{ github.event_name == 'workflow_run' && github.event.action == 'cancelled' }}
    steps:
      - name: Workflow Cancelled
        run: echo "Workflow has been cancelled"