name: Deploy and Control NestJS App

on:
  push:
    branches:
      - main
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to k3s Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.K3S_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.K3S_REGISTRY_URL }}/nestjs-app:${{ github.sha }} .
          docker push ${{ secrets.K3S_REGISTRY_URL }}/nestjs-app:${{ github.sha }}
          docker tag ${{ secrets.K3S_REGISTRY_URL }}/nestjs-app:${{ github.sha }} ${{ secrets.K3S_REGISTRY_URL }}/nestjs-app:latest
          docker push ${{ secrets.K3S_REGISTRY_URL }}/nestjs-app:latest

  notify-slack:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Notify Slack about the build
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "list_approve": "${{ secrets.SLACK_LIST_APPROVE }}",
              "title": "GitHub Action build result: ${{ job.status }}",
              "text": "Please check the commitment and approve if there are no problems.\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  pause-for-approval:
    runs-on: ubuntu-latest
    needs: [notify-slack, handle-decision]
    if: success() && needs.handle-decision.outputs.result == 'approve'
    steps:
      - name: Pause for Release Approval
        uses: softprops/turnstyle@v1
        with:
          abort-after-seconds: 14400 # 4 hours
          continue-message: "Approved for deployment"
          abort-message: "Deployment canceled"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-comments:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment'
    steps:
      - name: Check for Approval or Rejection Comment
        id: check_comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentBody = github.event.comment.body.toUpperCase();
            if (commentBody.includes("APPROVE")) {
              console.log("Approval comment detected.");
              return "approve";
            } else if (commentBody.includes("REJECT")) {
              console.log("Reject comment detected.");
              return "reject";
            }
            return "none";

  handle-decision:
    runs-on: ubuntu-latest
    needs: check-comments
    outputs:
      result: ${{ steps.check_comment.outputs.result }}
    if: needs.check-comments.outputs.result != 'none'
    steps:
      - name: Approval Actions
        if: needs.check-comments.outputs.result == 'approve'
        run: echo "Approved! Implement actions for approval here."
      - name: Rejection Actions
        if: needs.check-comments.outputs.result == 'reject'
        run: echo "Rejected! Implement actions for rejection here."
